// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/kim/v1/message.proto

package kimv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2CMessagePush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId     string                 `protobuf:"bytes,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Type           string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *C2CMessagePush) Reset() {
	*x = C2CMessagePush{}
	mi := &file_proto_kim_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CMessagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CMessagePush) ProtoMessage() {}

func (x *C2CMessagePush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kim_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CMessagePush.ProtoReflect.Descriptor instead.
func (*C2CMessagePush) Descriptor() ([]byte, []int) {
	return file_proto_kim_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *C2CMessagePush) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *C2CMessagePush) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *C2CMessagePush) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *C2CMessagePush) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *C2CMessagePush) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *C2CMessagePush) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *C2CMessagePush) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_proto_kim_v1_message_proto protoreflect.FileDescriptor

const file_proto_kim_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/kim/v1/message.proto\x12\x06kim.v1\"\xe3\x01\n" +
	"\x0eC2CMessagePush\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x04 \x01(\tR\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAtB/Z-github.com/project-kgo/kim/proto/kim/v1;kimv1b\x06proto3"

var (
	file_proto_kim_v1_message_proto_rawDescOnce sync.Once
	file_proto_kim_v1_message_proto_rawDescData []byte
)

func file_proto_kim_v1_message_proto_rawDescGZIP() []byte {
	file_proto_kim_v1_message_proto_rawDescOnce.Do(func() {
		file_proto_kim_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kim_v1_message_proto_rawDesc), len(file_proto_kim_v1_message_proto_rawDesc)))
	})
	return file_proto_kim_v1_message_proto_rawDescData
}

var file_proto_kim_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_kim_v1_message_proto_goTypes = []any{
	(*C2CMessagePush)(nil), // 0: kim.v1.C2CMessagePush
}
var file_proto_kim_v1_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_kim_v1_message_proto_init() }
func file_proto_kim_v1_message_proto_init() {
	if File_proto_kim_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kim_v1_message_proto_rawDesc), len(file_proto_kim_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_kim_v1_message_proto_goTypes,
		DependencyIndexes: file_proto_kim_v1_message_proto_depIdxs,
		MessageInfos:      file_proto_kim_v1_message_proto_msgTypes,
	}.Build()
	File_proto_kim_v1_message_proto = out.File
	file_proto_kim_v1_message_proto_goTypes = nil
	file_proto_kim_v1_message_proto_depIdxs = nil
}
