// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/project-kgo/kim/internal/app"
	"github.com/project-kgo/kim/internal/config"
	"github.com/project-kgo/kim/internal/data"
	"github.com/project-kgo/kim/internal/discovery/etcd"
	"github.com/project-kgo/kim/internal/gateway"
	"go.etcd.io/etcd/client/v3"
	"log/slog"
)

// Injectors from wire.go:

func Initialize(cfg config.Config, logger *slog.Logger) (*app.App, error) {
	data, err := ProvideData(cfg, logger)
	if err != nil {
		return nil, err
	}
	gatewayConfig := ProvideGatewayConfig(cfg)
	client, err := ProvideEtcdClient(cfg)
	if err != nil {
		return nil, err
	}
	builder := etcd.ResolverBuilder(client)
	gatewayClient, err := gateway.NewClient(gatewayConfig, logger, builder)
	if err != nil {
		return nil, err
	}
	appApp := app.New(cfg, logger, data, gatewayClient)
	return appApp, nil
}

// wire.go:

func ProvideData(cfg config.Config, logger *slog.Logger) (*data.Data, error) {
	return data.New(cfg.RedisDSN, cfg.DBDSN, logger)
}

func ProvideEtcdClient(cfg config.Config) (*clientv3.Client, error) {
	return clientv3.New(clientv3.Config{
		Endpoints: cfg.ETCDEndpoints,
		Username:  cfg.ETCDUsername,
		Password:  cfg.ETCDPassword,
	})
}

func ProvideGatewayConfig(cfg config.Config) gateway.Config {
	return gateway.Config{
		GatewayService: cfg.GatewayService,
		GatewayTimeout: cfg.GatewayTimeout,
	}
}
