// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kanengo/ku/snowflakex"
	"github.com/project-kgo/kim/internal/app"
	"github.com/project-kgo/kim/internal/config"
	"github.com/project-kgo/kim/internal/data"
	"github.com/project-kgo/kim/internal/discovery"
	"github.com/project-kgo/kim/internal/discovery/etcd"
	"github.com/project-kgo/kim/internal/gateway"
	"github.com/project-kgo/kim/internal/rpc"
	"github.com/project-kgo/kim/internal/service"
	"go.etcd.io/etcd/client/v3"
	"log/slog"
)

// Injectors from wire.go:

func Initialize(cfg config.Config, logger *slog.Logger) (*app.App, error) {
	data, err := ProvideData(cfg, logger)
	if err != nil {
		return nil, err
	}
	gatewayConfig := ProvideGatewayConfig(cfg)
	client, err := ProvideEtcdClient(cfg)
	if err != nil {
		return nil, err
	}
	builder := etcd.ResolverBuilder(client)
	gatewayClient, err := gateway.NewClient(gatewayConfig, logger, builder)
	if err != nil {
		return nil, err
	}
	serviceRegistry := ProvideEtcdRegistry(client, cfg)
	server, err := ProvideRPCServer(cfg, logger, serviceRegistry)
	if err != nil {
		return nil, err
	}
	node, err := ProvideSnowflakeNode()
	if err != nil {
		return nil, err
	}
	messageService := ProvideMessageService(logger, node, data)
	appApp := app.New(cfg, logger, data, gatewayClient, server, messageService)
	return appApp, nil
}

// wire.go:

func ProvideData(cfg config.Config, logger *slog.Logger) (*data.Data, error) {
	return data.New(cfg.RedisDSN, cfg.MQRedisDSN, cfg.DBDSN, logger)
}

func ProvideSnowflakeNode() (*snowflakex.Node, error) {
	return snowflakex.NewNode(1, 0)
}

func ProvideMessageService(logger *slog.Logger, node *snowflakex.Node, d *data.Data) *service.MessageService {
	return service.NewMessageService(logger, node, d.PubSub)
}

func ProvideEtcdClient(cfg config.Config) (*clientv3.Client, error) {
	return clientv3.New(clientv3.Config{
		Endpoints: cfg.ETCDEndpoints,
		Username:  cfg.ETCDUsername,
		Password:  cfg.ETCDPassword,
	})
}

func ProvideEtcdRegistry(cli *clientv3.Client, cfg config.Config) discovery.ServiceRegistry {
	return etcd.New(cli, cfg.ETCDTTL)
}

func ProvideGatewayConfig(cfg config.Config) gateway.Config {
	return gateway.Config{
		GatewayService: cfg.GatewayServiceName(),
		GatewayTimeout: cfg.GatewayTimeout,
	}
}

func ProvideRPCServer(cfg config.Config, logger *slog.Logger, registry discovery.ServiceRegistry) (*rpc.Server, error) {
	return rpc.NewServer(cfg, nil, logger, registry)
}
